### ISSUE TITLE
Provided dependencies can only be jars

### ISSUE THREAD

**Issue by ntimesc** [DynamicsCRM/Android-Activity-Tracker-for-Dynamics-CRM#1]
i have imported the ActivityTracker app for android in my studio and import the crmsdk2015 in it. 
now when i try to build ActivityTracker its showing following error 

> Error:Project crmsdk2015: provided dependencies can only be jars. com.android.support:appcompat-v7:aar:24.0.0 is an Android Library.

please see the attachment
![07-10-2016 5-31-06 pm](https://cloud.githubusercontent.com/assets/5063898/19189227/627a0202-8cb4-11e6-9800-871d7bcbb667.png)

**Comment by ntimesc** [comment]
i tried it with AAR too and here i am getting following error it seems ActivityTracker is not compatible with new CRM sdk 

![image](https://cloud.githubusercontent.com/assets/5063898/19192219/2af74146-8cc3-11e6-900a-cdf72030e983.png)

**Comment by JimDaly** [comment]
I'm afraid I can't address this specific issue, but if you are targeting CRM 2016, the newer Android mobile sample might be an option to consider. https://github.com/DynamicsCRM/Android-Activity-Tracker-for-Dynamics-CRM-Web-API. 

The newer sample requires Android Studio 2, JDK 1.8.0, Android 6. 

This older sample and the crmsdk2015 project it depends on were tested using Android API level 18 through 23 and Android Studio version 1.0 and later.  What is your environment?

**Comment by w9jds** [comment]
If you pulled the latest crmsdk and used that as your reference, then that is probably your problem. It was updated to better handle a lot of things, and that constructor probably no longer exists. If you want to use an older version. If you roll back to this commit you should be good.

[Initial Commit](https://github.com/DynamicsCRM/crm-mobilesdk-library-for-android/tree/b0b27a4a4ee6a37d187eef9240d154d3959115ea)

However, keep in mind that a ton of fixes and improvements were made to the sdk after this point.

**Comment by w9jds** [comment]
Also, I went ahead and made some quick changes to the project. It should now support the new crmsdk version, as well as it no longer requires you to pull the sdk and include it manually. I modified the gradle file to auto pull the latest code from github. In general the crmsdk on the outside didn't change much so all you have to do is import and build the project. 

Take a look at the pull request, or you can look at my fork directly [here](https://github.com/w9jds/Android-Activity-Tracker-for-Dynamics-CRM)

**Comment by JimDaly** [comment]
I've merged in Jeremy's changes which should fix this issue. If this doesn't address the problem, please re-open. Thanks @w9jds
